#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

(useradd -m  -u 1000 -U -d  /home/developer developer &>/dev/null ;true)
(usermod -G www-data developer &>/dev/null;true)
(usermod -G developer www-data &>/dev/null;true)
exec "$@"
